lane :use_OneSignal_profile do |options|
    profile_path = File.join(options[:project_dir], 'Assets/UCB/The_Diary_Of_Izida_Shadi_OneSignal_Profile.mobileprovision')
    FastlaneCore::ProvisioningProfile.install(profile_path)
    update_project_provisioning(
        xcodeproj: 'Unity-iPhone.xcodeproj',
        target_filter: 'OneSignalNotificationServiceExtension',
        profile: profile_path
    )
end